### ISSUE TITLE
gitlab artifacts broken

### ISSUE THREAD

**Issue by tomdaly** [DeveloperC286/conventional_commits_linter#35]
hi,

in an org project we use conventional commits linter/next version to validate commits. yesterday the builds started failing when trying to download the binary from the URL:
```
curl -L https://gitlab.com/DeveloperC/conventional_commits_linter/-/jobs/artifacts/bin-0.12.3/download?job=release-binary-compiling-x86_64-linux-musl -o ccl.zip
```

might this be related to the recent changes to mirroring?

**Comment by skipcloud** [comment]
Yeah the Gitlab config was deleted and the releases page no longer exists

**Comment by DeveloperC286** [comment]
@tomdaly @skipcloud Apologies I usually don't use the binaries so I didn't consider this. I will re-enable releases on GitLab and that should fix the 404's and then think about a long term solution.

**Comment by DeveloperC286** [comment]
> @tomdaly @skipcloud Sorry, it should be resolved for all my repositories now.

Verified you can download via links again.

So is this used at Deliveroo?

**Comment by tomdaly** [comment]
thank you @DeveloperC286 ! yeah it's in use at Deliveroo for a few shared repositories :)

**Comment by skipcloud** [comment]
Thanks for this :pray:
